### ISSUE TITLE
başlık tokeninde boşluklu veyahut özel karakterli isimlerin yazılması.

### ISSUE THREAD

**Issue by lazypwny751** [themispkg/baml#11]
header tokenlerde boşluk veyahut özel karakter kullanımının kısıtlanması ya da doğrudan değiştirilmesi, kodun işlevselliği açısından iyi olacaktır. Örnek olarak:
```txt
deneme;
            -> bu bir denemedir
```
yukarıda ki sorunsuz çalışan bir örnek lakin;
```txt
deneme 1 2;
                   -> bu bir denemedir
```
yukarıda ki gibi yazılırsa boşluğu da çeviriyor lakin değişken adlarında boşluk veya özel karakter olamaz.

**Comment by timurci** [comment]
Headerlarda İngilizce alfanumerik (a-z, A-Z, 0-9) ifadelerin haricindeki harfler `include/baml.h` dosyasındaki `INV_REPLACE` makrosuna atanan karakter değeriyle değiştirilerek yazdırılacaktır.

Bkz: https://github.com/themispkg/baml/commit/25087c6b4df2375823bbd5f91a65167be6c7b906
