### ISSUE TITLE
Kütüphane biçimine dönüştürüldü

### ISSUE THREAD

**Issue by alimkoca** [themispkg/baml#2]
Mükemmel-mükemmel daha ne olabilir ki?

**Comment by alimkoca** [comment]
Bence kütüphane iyileştirmesi iyi olur.

**Comment by lazypwny751** [comment]
elbette gerçekten güzel fikir aslına bakarsanız lakin biraz daha sadelik ve çekirdek kullanımı açısından düşündüğüm için arada kaldım asıl yapımcıya da danışıp pr'ı merge edeceğim tekrar açabilirsiniz.
